### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ferreusveritas** [ferreusveritas/WarpBook#1]
I'll use this issue here to track the progress of the new adaption of the mod

- [ ] Re-add Panicnot42's sounds
- [ ] Move recipes to JSON
- [ ] Add a warp fuel system

**Comment by shoverno2** [comment]
Warp fuel...
Sounds like thaumcraft))
Ans...
What about interesting compatibilityes with, for example, dim doors, thaumcraft and etc.
(it's already not "aggressive" to many mods, but what about interesting fusion things?)
